### ISSUE TITLE
Allow sorting of retrieved data

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#10]
Hi Kip,

Is there a way to sort the retrieved items? for example by createdon date ascending or descending.
I have looked into the docs and cannot find a way to do this easily.

**Comment by kip-dk** [comment]
all query methods take a sort argument that is a simple string. as i remember you have to add descending to the column name i you need descending sorting but that should be it. There is no help on meta data names for sorting, so you have to specify as a strin

ex

ascending is default
xrmcontextservice.query(yourprototypeinstance, youcondition, "yourprefix_fieldname")

xrmcontextservice.query(yourprototypeinstance, youcondition, "yourprefix_fieldname descending")

you can separate columns with ,  ex  "firstfield descending, nextfield"
