### ISSUE TITLE
XrmEntityKey does not return entityType

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#12]
Hi Kip,

I have deployed a webreource on an entity form and trying to use your service to retrieve the entity name.
The XrmEntityKey should give me back the id and the logical name of the entity but in this case it only returns the id of the record. See the screenshot below:

![image](https://user-images.githubusercontent.com/28629328/63851929-0e5d1b80-c98f-11e9-909b-c9770354b454.png)

I have gone through the docs and I think this is the method I need to use to achieve that, but let me know if I'm wrong.

**Comment by kip-dk** [comment]
Hi Christian. As i remember, 

could you see if the url in the webresource iframe has the parameter "typename". that is where is should be populated from.

**Comment by kip-dk** [comment]
If it is not in the url, it will try to extract it from the entity:

      result.id = window.parent["Xrm"]["Page"]["data"]["entity"]["getId"]();
      result.entityType = window.parent["Xrm"]["Page"]["data"]["entity"]["getEntityName"]();

**Comment by ChristianCRM** [comment]
Hi Kip,

You are correct. I'm using the newer version of Dynamics and I'm still learning the new API.

Thank you for your quick reply!

**Comment by kip-dk** [comment]
Xrm.Page.data is actually depreciated. I am currently preparing a version that gracefully handles that.

**Comment by kip-dk** [comment]
Closing the issue, if the entity id is there somewhere in the url, or in the parent, opener form, it will be found and populated.
