### ISSUE TITLE
Filter Parent based on child records

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#14]
Hi Kipon,

I have a requirement where I need to retrieve all records of a certain type and filter based on the relationship they have with child records.

Example: I want to retrieve all records of type A that do not have any child of Type B
Example 2: I want to retrieve all records of Type A where their children record of type B have a field called description that contains data.

You can find out more about what I'm trying to achieve following this [Link](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#filter-parent-records-based-on-values-of-child-records)

I can't figure out how to do it currently. Is it possible at all?

If not, could you implement it? And how long would it take for you to do it?

Thanks

Christian

**Comment by ChristianCRM** [comment]
Reading on the documentation, I see that I could use the fetchXml functionality. However I don't see how to use it in your documentation.

Any ideas?

**Comment by kip-dk** [comment]
Hi Christian

Alowing call to fetchxml would be pretty easy to impl. however parsing the result into entity strongly typed typescript classes is not trivial. I sometime have similar requirements in regards to complex queries that require "join" functionality like what you have in C# and the IOrganizationService, so i will take a look at the api and come back to you.

I am in process of establish a version 3.0 of the full library, that is 100% SOLID, only based on typescript with a single dependency to rxjs (it can be used with formscripts and other frameworks like vue and react), and that is where my focus i right now, but i will take a step to the side, and look into the joined query request to see how hard it would be. .. stay tuned :-)  i will keep you updated.

**Comment by kip-dk** [comment]
Condition now have a raw(filter: string) : Condition option, allowing you to add any type of filter. Of cause you have to figure out the exact syntax your self :-), - but at lease you can take advantage of all the other functions in the library for more trivial stuff.

In regards for fetchxml i will open another issue for that. It is a much larger task.

**Comment by ChristianCRM** [comment]
Hi Kipon,

Thank you very much for the effort in providing such functionality. However I'm trying to use but it does not add any filtering to the condition.
No matter what I type, it returns an empty condition.

Any ideas of what I might be doing wrong?

**Comment by kip-dk** [comment]
Hi Christian

can you share your condition expression, then i will setup a simple unit test to verify that the expression is rendered correctly.

**Comment by ChristianCRM** [comment]
`const condition = new Condition();
    condition.isActive();
    condition.raw('not crmd_crmdqe_quoteproductline_crmd_qe_orderdetail_quotedetailid/any()');`

the request only sends out the statecode filter without considering the second one. I've tried with other filters and they don't work either.

The environment is currently dev.

**Comment by kip-dk** [comment]
sorry for the inconvinience. The bug was totally trivial. The filter was created but not added to the stack within the Condition :-(.  version 2.2.13 solves the problem. please confirm that it works now so we can reclose the issue.

**Comment by ChristianCRM** [comment]
Hi Kipon,

Yes that work flawlessly! Many thanks!
