### ISSUE TITLE
.group(Operator.Or) doesn't create an or clause

### ISSUE THREAD

**Issue by bedaronco** [kip-dk/angular-xrmservice#2]
When I use the following example 
```
let condition = new Condtion()
    .where("name", Comparator.Contains, name)
    .isActive()
    .group(Operator.OR)
    .where("description", Comparator.Contains, name);
```

I end up with an 'and' clause for the description where instead of an 'or'.  To test out a fix I modified the generated javascript so that toQueryString looks like this when processing the children:

```
if (this.children != null && this.children.length > 0) {
    this.children.forEach(function (c) {
        if (c.operator == Operator.And) {
            opr = ' and ';
        }
        else {
            opr = ' or ';
        }
        result += opr + "(" + c.toQueryString(prototype) + ")";
    });
}
```

This way it using the operator from the child and not the last operator set from the last filter processed on the Condition.  Not sure if this is the proper fix or not.

**Comment by kip-dk** [comment]
Hi.
You have to add all conditions that should be or to SAME group. In your
example, there is only one where clause on the group, and therefore nothing
ends up to be or'ed.

I thing your comparator should look like this.

let condition = new Condtion()
    .isActive()
    .group(Operator.OR)
       .where("description", Comparator.Contains, name)

       .where("name", Comparator.Contains, name)


this will generate a condition that looks like this   statecode == 0
and (description contains(name) or name.contains(name))


If all three condition should be or,  it should be somthing like   new
Condition().group(Comparator.OR).where(...).where(...).where(...)

Let me know if this was helpfull.

regards
Kjeld


Mvh.
Kjeld Poulsen

Mail: kip@kipon.dk
Phone: +45 30 70 11 48
Web: http://kipon.dk
in: https://www.linkedin.com/in/kipon

Interesseret i angular og Dynamics 365 udvikling, se min seneste artikel om
emnet:

Angular and Dynamics 365
<https://www.linkedin.com/pulse/dynamics-365-web-resources-angular-4-kjeld-poulsen>


2018-05-19 15:21 GMT+02:00 Blaine <notifications@github.com>:

**Comment by kip-dk** [comment]
I have updated the documentation page for XrmContextService to better describe how group(..) is used. Hope this clearify the way to create OR conditions.
