### ISSUE TITLE
Could you provide sample in your documentation how to catch CRM specific errors

### ISSUE THREAD

**Issue by sdaniil** [kip-dk/angular-xrmservice#22]
Could you provide sample in your documentation how to catch CRM specific errors?

**Comment by kip-dk** [comment]
The Kipon.XrmService is 100% based on angular http client and rxjs, and is returning Observables. Please refer to the rxjs documentation for error handling.

I personally use the following patterns on the generated service:

myService.amethod().toPromise().then(r => handle success).catch(e => handle error)

but this is not specific to kipon.xrmservice.
